# Instantiate a Source Class

First, we import the necessary packages as follows.



In [3]:
from GravitationalWaves import utils, visualization, source
import numpy as np
import astropy.units as u
import matplotlib.pyplot as plt
from astropy.coordinates import SkyCoord

Now we can start by creating a random collection of possible LISA sources.


In [4]:
# create a random collection of sources
n_values = 1500
m_1 = np.random.uniform(0, 10, n_values) * u.Msun
m_2 = np.random.uniform(0, 10, n_values) * u.Msun
dist = np.random.normal(8, 1.5, n_values) * u.kpc
f_orb = 10**(-5 * np.random.power(3, n_values)) * u.Hz
ecc = 1 - np.random.power(3, n_values)

We can instantiate a Source class using these random sources as follows:



In [10]:
sources = source.Source(m_1=m_1, m_2=m_2, ecc=ecc, dist=dist, f_orb=f_orb, gw_lum_tol=0.05, stat_tol=1e-2,
                        interpolate_g=True, interpolate_sc=True,
                        sc_params={
                            "instrument": "LISA",
                            "custom_psd": None,
                            "t_obs": 4 * u.yr,
                            "L": 2.5e9 * u.m,
                            "approximate_R": False,
                            "confusion_noise": 'robson19'
                        })

## Strain functions

The source class provides a convenient wrapper around the functions from the strain module and allows you to compute either the strain or characteristic strain for any number of harmonics and any subset of the sources. Here, we calculate the strain for a number of harmonics on the same source class instance from above.



In [11]:
# compute h_c_n for every source for the first four harmonics
h_c_n4 = sources.get_h_c_n(harmonics=[1, 2, 3, 4])
print(h_c_n4)

[[1.16948650e-17 5.25842334e-18 1.57682968e-17 2.28738654e-17]
 [2.69316373e-18 1.21619372e-16 1.34623862e-17 1.10964600e-18]
 [1.19056818e-17 1.64377227e-16 5.78957754e-17 1.51271515e-17]
 ...
 [2.82379687e-19 2.78947324e-17 1.41489498e-18 5.34574202e-20]
 [1.52022088e-17 3.13765374e-17 4.55143934e-17 4.46870676e-17]
 [1.36344389e-17 2.63946400e-16 6.72769324e-17 1.27466337e-17]]
